export interface AdminUser {
    email: string;
    password: string;
    serviceId: number;
    serviceName: string;
}

// Map of 45 admin credentials for each government service
export const ADMIN_CREDENTIALS: Record<string, AdminUser> = {
    "master.admin@vaani.gov.in": { email: "master.admin@vaani.gov.in", password: "admin@master", serviceId: 0, serviceName: "All Services" },
    "aadhaar.admin@vaani.gov.in": { email: "aadhaar.admin@vaani.gov.in", password: "admin@aadhaar", serviceId: 1, serviceName: "Aadhaar Update" },
    "pan.admin@vaani.gov.in": { email: "pan.admin@vaani.gov.in", password: "admin@pan", serviceId: 2, serviceName: "PAN Card Application" },
    "voter.admin@vaani.gov.in": { email: "voter.admin@vaani.gov.in", password: "admin@voter", serviceId: 3, serviceName: "Voter ID Registration" },
    "birth.admin@vaani.gov.in": { email: "birth.admin@vaani.gov.in", password: "admin@birth", serviceId: 4, serviceName: "Birth Certificate" },
    "caste.admin@vaani.gov.in": { email: "caste.admin@vaani.gov.in", password: "admin@caste", serviceId: 5, serviceName: "Caste Certificate" },
    "income.admin@vaani.gov.in": { email: "income.admin@vaani.gov.in", password: "admin@income", serviceId: 6, serviceName: "Income Certificate" },
    "passport.admin@vaani.gov.in": { email: "passport.admin@vaani.gov.in", password: "admin@passport", serviceId: 7, serviceName: "Passport Application" },
    "driving.admin@vaani.gov.in": { email: "driving.admin@vaani.gov.in", password: "admin@driving", serviceId: 8, serviceName: "Driving License" },
    "vehicle.admin@vaani.gov.in": { email: "vehicle.admin@vaani.gov.in", password: "admin@vehicle", serviceId: 9, serviceName: "Vehicle Registration" },
    "hsrp.admin@vaani.gov.in": { email: "hsrp.admin@vaani.gov.in", password: "admin@hsrp", serviceId: 10, serviceName: "High Security HSRP" },
    "railway.admin@vaani.gov.in": { email: "railway.admin@vaani.gov.in", password: "admin@railway", serviceId: 11, serviceName: "Railway Senior Citizen" },
    "bank.admin@vaani.gov.in": { email: "bank.admin@vaani.gov.in", password: "admin@bank", serviceId: 12, serviceName: "Bank KYC Update" },
    "epf.admin@vaani.gov.in": { email: "epf.admin@vaani.gov.in", password: "admin@epf", serviceId: 13, serviceName: "EPF Withdrawal" },
    "itr.admin@vaani.gov.in": { email: "itr.admin@vaani.gov.in", password: "admin@itr", serviceId: 14, serviceName: "Income Tax Return" },
    "gst.admin@vaani.gov.in": { email: "gst.admin@vaani.gov.in", password: "admin@gst", serviceId: 15, serviceName: "GST Registration" },
    "mudra.admin@vaani.gov.in": { email: "mudra.admin@vaani.gov.in", password: "admin@mudra", serviceId: 16, serviceName: "Personal Loan Mudra" },
    "oldage.admin@vaani.gov.in": { email: "oldage.admin@vaani.gov.in", password: "admin@oldage", serviceId: 17, serviceName: "Old Age Pension" },
    "widow.admin@vaani.gov.in": { email: "widow.admin@vaani.gov.in", password: "admin@widow", serviceId: 18, serviceName: "Widow Pension" },
    "kisan.admin@vaani.gov.in": { email: "kisan.admin@vaani.gov.in", password: "admin@kisan", serviceId: 19, serviceName: "Kisan Samman Nidhi" },
    "ration.admin@vaani.gov.in": { email: "ration.admin@vaani.gov.in", password: "admin@ration", serviceId: 20, serviceName: "Ration Card Application" },
    "postmatric.admin@vaani.gov.in": { email: "postmatric.admin@vaani.gov.in", password: "admin@postmatric", serviceId: 21, serviceName: "Post-Matric Scholarship" },
    "prematric.admin@vaani.gov.in": { email: "prematric.admin@vaani.gov.in", password: "admin@prematric", serviceId: 22, serviceName: "Pre-Matric Scholarship" },
    "ayushman.admin@vaani.gov.in": { email: "ayushman.admin@vaani.gov.in", password: "admin@ayushman", serviceId: 23, serviceName: "Ayushman Bharat" },
    "disability.admin@vaani.gov.in": { email: "disability.admin@vaani.gov.in", password: "admin@disability", serviceId: 24, serviceName: "Disability Certificate" },
    "mgnrega.admin@vaani.gov.in": { email: "mgnrega.admin@vaani.gov.in", password: "admin@mgnrega", serviceId: 25, serviceName: "MGNREGA Job Card" },
    "udyam.admin@vaani.gov.in": { email: "udyam.admin@vaani.gov.in", password: "admin@udyam", serviceId: 26, serviceName: "Udyam Registration" },
    "fssai.admin@vaani.gov.in": { email: "fssai.admin@vaani.gov.in", password: "admin@fssai", serviceId: 27, serviceName: "FSSAI License" },
    "pm-awas.admin@vaani.gov.in": { email: "pm-awas.admin@vaani.gov.in", password: "admin@pm-awas", serviceId: 28, serviceName: "PM Awas Yojana" },
    "electricity.admin@vaani.gov.in": { email: "electricity.admin@vaani.gov.in", password: "admin@electricity", serviceId: 29, serviceName: "New Electricity Connection" },
    "water.admin@vaani.gov.in": { email: "water.admin@vaani.gov.in", password: "admin@water", serviceId: 30, serviceName: "Water Pipe Connection" },
    "ujjwala.admin@vaani.gov.in": { email: "ujjwala.admin@vaani.gov.in", password: "admin@ujjwala", serviceId: 31, serviceName: "Gas Connection Ujjwala" },
    "soil.admin@vaani.gov.in": { email: "soil.admin@vaani.gov.in", password: "admin@soil", serviceId: 32, serviceName: "Soil Health Card" },
    "kcc.admin@vaani.gov.in": { email: "kcc.admin@vaani.gov.in", password: "admin@kcc", serviceId: 33, serviceName: "Kisan Credit Card" },
    "pesticide.admin@vaani.gov.in": { email: "pesticide.admin@vaani.gov.in", password: "admin@pesticide", serviceId: 34, serviceName: "Pesticide License" },
    "legalheir.admin@vaani.gov.in": { email: "legalheir.admin@vaani.gov.in", password: "admin@legalheir", serviceId: 35, serviceName: "Legal Heir Certificate" },
    "marriage.admin@vaani.gov.in": { email: "marriage.admin@vaani.gov.in", password: "admin@marriage", serviceId: 36, serviceName: "Marriage Registration" },
    "death.admin@vaani.gov.in": { email: "death.admin@vaani.gov.in", password: "admin@death", serviceId: 37, serviceName: "Death Registration" },
    "dsc.admin@vaani.gov.in": { email: "dsc.admin@vaani.gov.in", password: "admin@dsc", serviceId: 38, serviceName: "Digital Signature Cert" },
    "domain.admin@vaani.gov.in": { email: "domain.admin@vaani.gov.in", password: "admin@domain", serviceId: 39, serviceName: "Domain Registration (.in)" },
    "arms.admin@vaani.gov.in": { email: "arms.admin@vaani.gov.in", password: "admin@arms", serviceId: 40, serviceName: "Arms License" },
    "ex-service.admin@vaani.gov.in": { email: "ex-service.admin@vaani.gov.in", password: "admin@ex-service", serviceId: 41, serviceName: "Ex-Servicemen Identity" },
    "senior.admin@vaani.gov.in": { email: "senior.admin@vaani.gov.in", password: "admin@senior", serviceId: 42, serviceName: "Senior Citizen Card" },
    "transgender.admin@vaani.gov.in": { email: "transgender.admin@vaani.gov.in", password: "admin@transgender", serviceId: 43, serviceName: "Transgender ID Card" },
    "sc-st.admin@vaani.gov.in": { email: "sc-st.admin@vaani.gov.in", password: "admin@sc-st", serviceId: 44, serviceName: "SC/ST Fellowship" },
    "minority.admin@vaani.gov.in": { email: "minority.admin@vaani.gov.in", password: "admin@minority", serviceId: 45, serviceName: "Minority Scholarship" },
};
