// Indian States and Districts Data

export interface District {
  name: string;
  nameHi?: string;
  nameTe?: string;
  nameKn?: string;
  nameTa?: string;
  nameMl?: string;
  nameMr?: string;
  nameBn?: string;
  nameGu?: string;
  nameOr?: string;
  namePa?: string;
  nameUr?: string;
}

export interface State {
  name: string;
  nameHi: string;
  nameTe: string;
  nameKn?: string;
  nameTa?: string;
  nameMl?: string;
  nameMr?: string;
  nameBn?: string;
  nameGu?: string;
  nameOr?: string;
  namePa?: string;
  nameUr?: string;
  code: string;
  districts: District[];
}

export const INDIAN_STATES: State[] = [
  {
    name: "Andhra Pradesh",
    nameHi: "आंध्र प्रदेश",
    nameTe: "ఆంధ్ర ప్రదేశ్",
    nameTa: "ஆந்திரப் பிரதேசம்",
    nameKn: "ಆಂಧ್ರ ಪ್ರದೇಶ",
    nameMl: "ആന്ധ്രാപ്രദേശ്",
    nameMr: "आंध्र प्रदेश",
    nameBn: "অন্ধ্রপ্রদেশ",
    nameGu: "આંધ્ર પ્રદેશ",
    nameOr: "ଆନ୍ଧ୍ରପ୍ରଦେଶ",
    namePa: "ਆਂਧਰਾ ਪ੍ਰਦੇਸ਼",
    nameUr: "آندھرا پردیش",
    code: "AP",
    districts: [
      { name: "Anantapur", nameHi: "अनंतपुर", nameTe: "అనంతపురం", nameGu: "અનંતપુર", nameTa: "அனந்தபூர்", nameKn: "ಅನಂತಪುರ", nameMl: "അനന്തപൂർ", nameMr: "अनंतपूर", nameBn: "অনন্তপুর", nameOr: "ଅନନ୍ତପୁର", namePa: "ਅਨੰਤਪੁਰ", nameUr: "اننت پور" },
      { name: "Chittoor", nameHi: "चित्तूर", nameTe: "చిత్తూరు", nameGu: "ચિત્તૂર", nameTa: "சித்தூர்", nameKn: "ಚಿತ್ತೂರು", nameMl: "ചിറ്റൂർ", nameMr: "चित्तूर", nameBn: "চিত্তুর", nameOr: "ଚିତ୍ତୂର", namePa: "ਚਿਤੂਰ", nameUr: "چتور" },
      { name: "East Godavari", nameHi: "पूर्व गोदावरी", nameTe: "తూర్పు గోదావరి", nameGu: "પૂર્વ ગોદાવરી", nameTa: "கிழக்கு கோதாவரி", nameKn: "ಪೂರ್ವ ಗೋದಾವರಿ", nameMl: "കിഴക്കൻ ഗോദാവരി", nameMr: "पूर्व गोदावरी", nameBn: "পূর্ব গোদাবরী", nameOr: "ପୂର୍ବ ଗୋଦାବରୀ", namePa: "ਪੂਰਬੀ ਗੋਦਾਵਰੀ", nameUr: "مشرقی گوداوری" },
      { name: "Guntur", nameHi: "गुंटूर", nameTe: "గుంటూరు", nameGu: "ગુંટુર", nameTa: "குண்டூர்", nameKn: "ಗುಂಟೂರು", nameMl: "ഗുണ്ടൂർ", nameMr: "गुंटूर", nameBn: "ગુন্টુર", nameOr: "ଗୁଣ୍ଟୁର", namePa: "ਗੁੰਟੂਰ", nameUr: "گنٹور" },
      { name: "Kadapa", nameHi: "कडप्पा", nameTe: "కడప", nameGu: "કડપ્પા", nameTa: "கடப்பா", nameKn: "ಕಡಪ", nameMl: "കടപ്പ", nameMr: "कडप्पा", nameBn: "কডপ্পা", nameOr: "କଡ଼ପ୍ପା", namePa: "ਕਡੱਪਾ", nameUr: "کڈپہ" },
      { name: "Krishna", nameHi: "कृष्णा", nameTe: "కృష్ణా", nameGu: "કૃષ્ણા", nameTa: "கிருஷ்ணா", nameKn: "ಕೃಷ್ಣಾ", nameMl: "കൃഷ്ണ", nameMr: "कृष्णा", nameBn: "কৃষ্ণা", nameOr: "କୃଷ୍ଣା", namePa: "ਕ੍ਰਿਸ਼ਨਾ", nameUr: "کرشنا" },
      { name: "Kurnool", nameHi: "कुर्नूल", nameTe: "కర్నూలు", nameGu: "કુર્નૂલ", nameTa: "கர்னூல்", nameKn: "ಕರ್ನೂಲು", nameMl: "കർണൂൽ", nameMr: "कुर्नूल", nameBn: "কর্নুল", nameOr: "କୁର୍ନୂଲ", namePa: "ਕੁਰਨੂਲ", nameUr: "کرنول" },
      { name: "Nellore", nameHi: "नेल्लोर", nameTe: "నెల్లూరు", nameGu: "નેલોર", nameTa: "நெல்லூர்", nameKn: "ನೆಲ್ಲೂರು", nameMl: "നെല്ലൂർ", nameMr: "नेल्लोर", nameBn: "নেল্লোর", nameOr: "ନେଲ୍ଲୋର", namePa: "ਨੇਲੋਰ", nameUr: "نیلور" },
      { name: "Prakasam", nameHi: "प्रकाशम", nameTe: "ప్రకాశం", nameGu: "પ્રકાશમ", nameTa: "பிரகாசம்", nameKn: "ಪ್ರಕಾಶಂ", nameMl: "പ്രകാശം", nameMr: "प्रकाशम", nameBn: "প্রকাশম", nameOr: "ପ୍ରକାଶମ", namePa: "ਪ੍ਰਕਾਸ਼ਮ", nameUr: "پرکاشم" },
      { name: "Srikakulam", nameHi: "श्रीकाकुलम", nameTe: "శ్రీకాకుళం", nameGu: "શ્રીકાકુલમ", nameTa: "ஸ்ரீகாகுளம்", nameKn: "ಶ್ರೀಕಾಕುಳಂ", nameMl: "ശ്രീകാകുളം", nameMr: "श्रीकाकुलम", nameBn: "শ্রীকাকুলাম", nameOr: "ଶ୍ରୀକାକୁଲମ", namePa: "ਸ਼੍ਰੀਕਾਕੁਲਮ", nameUr: "سریکاکولم" },
      { name: "Visakhapatnam", nameHi: "विशाखापट्टनम", nameTe: "విశాఖపట్నం", nameGu: "વિશાખાપટ્ટનમ", nameTa: "விசாகப்பட்டினம்", nameKn: "ವಿಶಾಖಪಟ್ಟಣಂ", nameMl: "വിശാഖപട്ടണം", nameMr: "विशाखापट्टणम", nameBn: "বিশাখাপত্তনમ", nameOr: "ବିଶାଖାପଟ୍ଟନମ", namePa: "ਵਿਸ਼ਾਖਾਪਟਨਮ", nameUr: "وشاکھاپٹنم" },
      { name: "Vizianagaram", nameHi: "विजयनगरम", nameTe: "విజయనగరం", nameGu: "વિજયનગરમ", nameTa: "விஜயநகரம்", nameKn: "ವಿಜಯನಗರಂ", nameMl: "വിജയനഗരം", nameMr: "विजयनगरम", nameBn: "বিজয়নগরম", nameOr: "ବିଜୟନଗରମ", namePa: "ਵਿਜੇਨਗਰਮ", nameUr: "وجیانگرم" },
      { name: "West Godavari", nameHi: "पश्चिम गोदावरी", nameTe: "పశ్చిమ గోదావరి", nameGu: "પશ્ચિમ ગોદાવરી", nameTa: "மேற்கு கோதாவரி", nameKn: "ಪಶ್ಚಿಮ ಗೋದಾವರಿ", nameMl: "പശ്ചിമ ഗോദാവരി", nameMr: "पश्चिम गोदावरी", nameBn: "পশ্চিম গোদাবরী", nameOr: "ପଶ୍ଚିମ ଗୋଦାବରୀ", namePa: "ਪੱਛਮੀ ਗੋਦਾਵਰੀ", nameUr: "مغربی گوداوری" },
    ]
  },
  {
    name: "Arunachal Pradesh",
    nameHi: "अरुणाचल प्रदेश",
    nameTe: "అరుణాచల్ ప్రదేశ్",
    nameTa: "அருணாச்சலப் பிரதேசம்",
    nameKn: "ಅರುಣಾಚಲ ಪ್ರದೇಶ",
    nameMl: "അരുണാചൽ പ്രദേശ്",
    nameMr: "अरुणाचल प्रदेश",
    nameBn: "অরুণাচল প্রদেশ",
    nameGu: "અરુણાચલ પ્રદેશ",
    nameOr: "ଅରୁଣାଚଳ ପ୍ରଦେଶ",
    namePa: "ਅਰੁਣਾਚਲ ਪ੍ਰਦੇਸ਼",
    nameUr: "اروناچل پردیش",
    code: "AR",
    districts: [
      { name: "Anjaw" },
      { name: "Changlang" },
      { name: "Dibang Valley" },
      { name: "East Kameng" },
      { name: "East Siang" },
      { name: "Itanagar Capital Complex" },
      { name: "Kurung Kumey" },
      { name: "Lohit" },
      { name: "Lower Dibang Valley" },
      { name: "Lower Subansiri" },
      { name: "Papum Pare" },
      { name: "Tawang" },
      { name: "Tirap" },
      { name: "Upper Siang" },
      { name: "Upper Subansiri" },
      { name: "West Kameng" },
      { name: "West Siang" },
    ]
  },
  {
    name: "Assam",
    nameHi: "असम",
    nameTe: "అస్సాం",
    nameTa: "அசாம்",
    nameKn: "ಅಸ್ಸಾಂ",
    nameMl: "അസം",
    nameMr: "आसाम",
    nameBn: "অসম",
    nameGu: "આસામ",
    nameOr: "ଆସାମ",
    namePa: "ਅਸਾਮ",
    nameUr: "آسام",
    code: "AS",
    districts: [
      { name: "Baksa" },
      { name: "Barpeta" },
      { name: "Biswanath" },
      { name: "Bongaigaon" },
      { name: "Cachar" },
      { name: "Charaideo" },
      { name: "Chirang" },
      { name: "Darrang" },
      { name: "Dhemaji" },
      { name: "Dhubri" },
      { name: "Dibrugarh" },
      { name: "Goalpara" },
      { name: "Golaghat" },
      { name: "Guwahati" },
      { name: "Hailakandi" },
      { name: "Jorhat" },
      { name: "Kamrup" },
      { name: "Karbi Anglong" },
      { name: "Karimganj" },
      { name: "Kokrajhar" },
      { name: "Lakhimpur" },
      { name: "Majuli" },
      { name: "Morigaon" },
      { name: "Nagaon" },
      { name: "Nalbari" },
      { name: "Sivasagar" },
      { name: "Sonitpur" },
      { name: "Tinsukia" },
      { name: "Udalguri" },
    ]
  },
  {
    name: "Bihar",
    nameHi: "बिहार",
    nameTe: "బీహార్",
    nameTa: "பீகார்",
    nameKn: "ಬಿಹಾರ",
    nameMl: "ബീഹാർ",
    nameMr: "बिहार",
    nameBn: "বিহার",
    nameGu: "બિહાર",
    nameOr: "ବିହାର",
    namePa: "ਬਿਹਾਰ",
    nameUr: "بہار",
    code: "BR",
    districts: [
      { name: "Araria" },
      { name: "Arwal" },
      { name: "Aurangabad" },
      { name: "Banka" },
      { name: "Begusarai" },
      { name: "Bhagalpur" },
      { name: "Bhojpur" },
      { name: "Buxar" },
      { name: "Darbhanga" },
      { name: "East Champaran" },
      { name: "Gaya" },
      { name: "Gopalganj" },
      { name: "Jamui" },
      { name: "Jehanabad" },
      { name: "Kaimur" },
      { name: "Katihar" },
      { name: "Khagaria" },
      { name: "Kishanganj" },
      { name: "Lakhisarai" },
      { name: "Madhepura" },
      { name: "Madhubani" },
      { name: "Munger" },
      { name: "Muzaffarpur" },
      { name: "Nalanda" },
      { name: "Nawada" },
      { name: "Patna" },
      { name: "Purnia" },
      { name: "Rohtas" },
      { name: "Saharsa" },
      { name: "Samastipur" },
      { name: "Saran" },
      { name: "Sheikhpura" },
      { name: "Sheohar" },
      { name: "Sitamarhi" },
      { name: "Siwan" },
      { name: "Supaul" },
      { name: "Vaishali" },
      { name: "West Champaran" },
    ]
  },
  {
    name: "Chhattisgarh",
    nameHi: "छत्तीसगढ़",
    nameTe: "ఛత్తీస్‌గఢ్",
    nameTa: "சத்தீஸ்கர்",
    nameKn: "ಛತ್ತೀಸ್‌ಗಢ್",
    nameMl: "ഛത്തീസ്ഗഢ്",
    nameMr: "छत्तीसगड",
    nameBn: "ছত্তিশগড়",
    nameGu: "છત્તીસગઢ",
    nameOr: "ଛତିଶଗଡ",
    namePa: "ਛੱਤੀਸਗੜ੍ਹ",
    nameUr: "چھتیس گڑھ",
    code: "CG",
    districts: [
      { name: "Balod" },
      { name: "Baloda Bazar" },
      { name: "Balrampur" },
      { name: "Bastar" },
      { name: "Bemetara" },
      { name: "Bijapur" },
      { name: "Bilaspur" },
      { name: "Dantewada" },
      { name: "Dhamtari" },
      { name: "Durg" },
      { name: "Gariaband" },
      { name: "Janjgir-Champa" },
      { name: "Jashpur" },
      { name: "Kabirdham" },
      { name: "Kanker" },
      { name: "Kondagaon" },
      { name: "Korba" },
      { name: "Koriya" },
      { name: "Mahasamund" },
      { name: "Mungeli" },
      { name: "Narayanpur" },
      { name: "Raigarh" },
      { name: "Raipur" },
      { name: "Rajnandgaon" },
      { name: "Sukma" },
      { name: "Surajpur" },
      { name: "Surguja" },
    ]
  },
  {
    name: "Delhi",
    nameHi: "दिल्ली",
    nameTe: "ఢిల్లీ",
    nameTa: "டெல்லி",
    nameKn: "ದೆಹಲಿ",
    nameMl: "ഡൽഹി",
    nameMr: "दिल्ली",
    nameBn: "দিল্লি",
    nameGu: "દિલ્હી",
    nameOr: "ଦିଲ୍ଲୀ",
    namePa: "ਦਿੱਲੀ",
    nameUr: "دہلی",
    code: "DL",
    districts: [
      { name: "Central Delhi" },
      { name: "East Delhi" },
      { name: "New Delhi" },
      { name: "North Delhi" },
      { name: "North East Delhi" },
      { name: "North West Delhi" },
      { name: "Shahdara" },
      { name: "South Delhi" },
      { name: "South East Delhi" },
      { name: "South West Delhi" },
      { name: "West Delhi" },
    ]
  },
  {
    name: "Goa",
    nameHi: "गोवा",
    nameTe: "గోవా",
    nameTa: "கோவா",
    nameKn: "ಗೋವಾ",
    nameMl: "ഗോവ",
    nameMr: "गोवा",
    nameBn: "গোয়া",
    nameGu: "ગોવા",
    nameOr: "ଗୋଆ",
    namePa: "ਗੋਆ",
    nameUr: "گوا",
    code: "GA",
    districts: [
      { name: "North Goa" },
      { name: "South Goa" },
    ]
  },
  {
    name: "Gujarat",
    nameHi: "गुजरात",
    nameTe: "గుజరాత్",
    nameGu: "ગુજરાત",
    nameTa: "குஜராத்",
    nameKn: "ಗುಜರಾತ್",
    nameMl: "ഗുജറാത്ത്",
    nameMr: "गुजरात",
    nameBn: "গুজরাট",
    nameOr: "ଗୁଜୁରାଟ",
    namePa: "ਗੁਜਰਾਤ",
    nameUr: "گجرات",
    code: "GJ",
    districts: [
      { name: "Ahmedabad" },
      { name: "Amreli" },
      { name: "Anand" },
      { name: "Aravalli" },
      { name: "Banaskantha" },
      { name: "Bharuch" },
      { name: "Bhavnagar" },
      { name: "Botad" },
      { name: "Chhota Udaipur" },
      { name: "Dahod" },
      { name: "Dang" },
      { name: "Devbhoomi Dwarka" },
      { name: "Gandhinagar" },
      { name: "Gir Somnath" },
      { name: "Jamnagar" },
      { name: "Junagadh" },
      { name: "Kheda" },
      { name: "Kutch" },
      { name: "Mahisagar" },
      { name: "Mehsana" },
      { name: "Morbi" },
      { name: "Narmada" },
      { name: "Navsari" },
      { name: "Panchmahal" },
      { name: "Patan" },
      { name: "Porbandar" },
      { name: "Rajkot" },
      { name: "Sabarkantha" },
      { name: "Surat" },
      { name: "Surendranagar" },
      { name: "Tapi" },
      { name: "Vadodara" },
      { name: "Valsad" },
    ]
  },
  {
    name: "Haryana",
    nameHi: "हरियाणा",
    nameTe: "హర్యానా",
    nameTa: "ஹரியானா",
    nameKn: "ಹರಿಯಾಣ",
    nameMl: "ഹരിയാന",
    nameMr: "हरियाणा",
    nameBn: "হরিয়ানা",
    nameGu: "હરિયાણા",
    nameOr: "ହରିଆଣା",
    namePa: "ਹਰਿਆਣਾ",
    nameUr: "ہریانہ",
    code: "HR",
    districts: [
      { name: "Ambala" },
      { name: "Bhiwani" },
      { name: "Charkhi Dadri" },
      { name: "Faridabad" },
      { name: "Fatehabad" },
      { name: "Gurugram" },
      { name: "Hisar" },
      { name: "Jhajjar" },
      { name: "Jind" },
      { name: "Kaithal" },
      { name: "Karnal" },
      { name: "Kurukshetra" },
      { name: "Mahendragarh" },
      { name: "Nuh" },
      { name: "Palwal" },
      { name: "Panchkula" },
      { name: "Panipat" },
      { name: "Rewari" },
      { name: "Rohtak" },
      { name: "Sirsa" },
      { name: "Sonipat" },
      { name: "Yamunanagar" },
    ]
  },
  {
    name: "Himachal Pradesh",
    nameHi: "हिमाचल प्रदेश",
    nameTe: "హిమాచల్ ప్రదేశ్",
    nameTa: "இமாச்சலப் பிரதேசம்",
    nameKn: "ಹಿಮಾಚಲ ಪ್ರದೇಶ",
    nameMl: "ഹിമാചൽ പ്രദേശ്",
    nameMr: "हिमाचल प्रदेश",
    nameBn: "হিমাচল প্রদেশ",
    nameGu: "હિમાચલ પ્રદેશ",
    nameOr: "ହିମାଚଳ ପ୍ରଦେଶ",
    namePa: "हिमाचल प्रदेश",
    nameUr: "ہماچل پردیش",
    code: "HP",
    districts: [
      { name: "Bilaspur" },
      { name: "Chamba" },
      { name: "Hamirpur" },
      { name: "Kangra" },
      { name: "Kinnaur" },
      { name: "Kullu" },
      { name: "Lahaul and Spiti" },
      { name: "Mandi" },
      { name: "Shimla" },
      { name: "Sirmaur" },
      { name: "Solan" },
      { name: "Una" },
    ]
  },
  {
    name: "Jharkhand",
    nameHi: "झारखंड",
    nameTe: "జార్ఖండ్",
    nameTa: "ஜார்க்கண்ட்",
    nameKn: "ಜಾರ್ಖಂಡ್",
    nameMl: "ജാർഖണ്ഡ്",
    nameMr: "झारखंड",
    nameBn: "ঝাড়খণ্ড",
    nameGu: "ઝારખંડ",
    nameOr: "ଝାଡ଼ଖଣ୍ଡ",
    namePa: "ਝਾਰਖੰਡ",
    nameUr: "جھارکھنڈ",
    code: "JH",
    districts: [
      { name: "Bokaro" },
      { name: "Chatra" },
      { name: "Deoghar" },
      { name: "Dhanbad" },
      { name: "Dumka" },
      { name: "East Singhbhum" },
      { name: "Garhwa" },
      { name: "Giridih" },
      { name: "Godda" },
      { name: "Gumla" },
      { name: "Hazaribagh" },
      { name: "Jamtara" },
      { name: "Khunti" },
      { name: "Koderma" },
      { name: "Latehar" },
      { name: "Lohardaga" },
      { name: "Pakur" },
      { name: "Palamu" },
      { name: "Ramgarh" },
      { name: "Ranchi" },
      { name: "Sahebganj" },
      { name: "Seraikela Kharsawan" },
      { name: "Simdega" },
      { name: "West Singhbhum" },
    ]
  },
  {
    name: "Karnataka",
    nameHi: "कर्नाटक",
    nameTe: "కర్ణాటక",
    nameKn: "ಕರ್ನಾಟಕ",
    nameTa: "கர்நாடகா",
    nameMl: "കർണാടക",
    nameMr: "कर्नाटक",
    nameBn: "কর্ণাটক",
    nameGu: "કર્ણાટક",
    nameOr: "କର୍ଣ୍ଣାଟକ",
    namePa: "ਕਰਨਾਟਕ",
    nameUr: "کرناٹک",
    code: "KA",
    districts: [
      { name: "Bagalkot" },
      { name: "Ballari" },
      { name: "Belagavi" },
      { name: "Bengaluru Rural" },
      { name: "Bengaluru Urban", nameKn: "ಬೆಂಗಳೂರು ನಗರ" },
      { name: "Bidar" },
      { name: "Chamarajanagar" },
      { name: "Chikballapur" },
      { name: "Chikkamagaluru" },
      { name: "Chitradurga" },
      { name: "Dakshina Kannada" },
      { name: "Davanagere" },
      { name: "Hubballi-Dharwad", nameKn: "ಹುಬ್ಬಳ್ಳಿ-ಧಾರವಾಡ" },
      { name: "Gadag" },
      { name: "Hassan" },
      { name: "Haveri" },
      { name: "Kalaburagi" },
      { name: "Kodagu" },
      { name: "Kolar" },
      { name: "Koppal" },
      { name: "Mandya" },
      { name: "Mysuru", nameKn: "ಮೈಸೂರು" },
      { name: "Raichur" },
      { name: "Ramanagara" },
      { name: "Shivamogga" },
      { name: "Tumakuru" },
      { name: "Udupi" },
      { name: "Uttara Kannada" },
      { name: "Vijayapura" },
      { name: "Yadgir" },
    ]
  },
  {
    name: "Kerala",
    nameHi: "केरल",
    nameTe: "కేరళ",
    nameMl: "കേരളം",
    nameTa: "கேரளா",
    nameKn: "ಕೇರಳ",
    nameMr: "केरळ",
    nameBn: "কেরল",
    nameGu: "કેરળ",
    nameOr: "କେରଳ",
    namePa: "ਕੇਰਲ",
    nameUr: "کیرالہ",
    code: "KL",
    districts: [
      { name: "Alappuzha" },
      { name: "Ernakulam" },
      { name: "Idukki" },
      { name: "Kannur" },
      { name: "Kasaragod" },
      { name: "Kollam" },
      { name: "Kottayam" },
      { name: "Kozhikode" },
      { name: "Malappuram" },
      { name: "Palakkad" },
      { name: "Pathanamthitta" },
      { name: "Thiruvananthapuram" },
      { name: "Thrissur" },
      { name: "Wayanad" },
    ]
  },
  {
    name: "Madhya Pradesh",
    nameHi: "मध्य प्रदेश",
    nameTe: "మధ్యప్రదేశ్",
    nameTa: "மத்தியப் பிரதேசம்",
    nameKn: "ಮಧ್ಯ ಪ್ರದೇಶ",
    nameMl: "മധ്യപ്രദേശ്",
    nameMr: "मध्य प्रदेश",
    nameBn: "মধ্যপ্রদেশ",
    nameGu: "મધ્ય પ્રદેશ",
    nameOr: "ମଧ୍ୟପ୍ରଦେଶ",
    namePa: "ਮੱਧ ਪ੍ਰਦੇਸ਼",
    nameUr: "مدھیہ پردیش",
    code: "MP",
    districts: [
      { name: "Agar Malwa" },
      { name: "Alirajpur" },
      { name: "Anuppur" },
      { name: "Ashoknagar" },
      { name: "Balaghat" },
      { name: "Barwani" },
      { name: "Betul" },
      { name: "Bhind" },
      { name: "Bhopal" },
      { name: "Burhanpur" },
      { name: "Chhatarpur" },
      { name: "Chhindwara" },
      { name: "Damoh" },
      { name: "Datia" },
      { name: "Dewas" },
      { name: "Dhar" },
      { name: "Dindori" },
      { name: "Guna" },
      { name: "Gwalior" },
      { name: "Harda" },
      { name: "Hoshangabad" },
      { name: "Indore" },
      { name: "Jabalpur" },
      { name: "Jhabua" },
      { name: "Katni" },
      { name: "Khandwa" },
      { name: "Khargone" },
      { name: "Mandla" },
      { name: "Mandsaur" },
      { name: "Morena" },
      { name: "Narsinghpur" },
      { name: "Neemuch" },
      { name: "Panna" },
      { name: "Raisen" },
      { name: "Rajgarh" },
      { name: "Ratlam" },
      { name: "Rewa" },
      { name: "Sagar" },
      { name: "Satna" },
      { name: "Sehore" },
      { name: "Seoni" },
      { name: "Shahdol" },
      { name: "Shajapur" },
      { name: "Sheopur" },
      { name: "Shivpuri" },
      { name: "Sidhi" },
      { name: "Singrauli" },
      { name: "Tikamgarh" },
      { name: "Ujjain" },
      { name: "Umaria" },
      { name: "Vidisha" },
    ]
  },
  {
    name: "Maharashtra",
    nameHi: "महाराष्ट्र",
    nameTe: "మహారాష్ట్ర",
    nameMr: "महाराष्ट्र",
    nameTa: "மகாராஷ்டிரா",
    nameKn: "ಮಹಾರಾಷ್ಟ್ರ",
    nameMl: "മഹാരാഷ്ട്ര",
    nameBn: "মহারাষ্ট্র",
    nameGu: "મહારાષ્ટ્ર",
    nameOr: "ମହାରାଷ୍ଟ୍ର",
    namePa: "ਮਹਾਰਾਸ਼ਟਰ",
    nameUr: "مہاراشٹر",
    code: "MH",
    districts: [
      { name: "Ahmednagar" },
      { name: "Akola" },
      { name: "Amravati" },
      { name: "Aurangabad" },
      { name: "Beed" },
      { name: "Bhandara" },
      { name: "Buldhana" },
      { name: "Chandrapur" },
      { name: "Dhule" },
      { name: "Gadchiroli" },
      { name: "Gondia" },
      { name: "Hingoli" },
      { name: "Jalgaon" },
      { name: "Jalna" },
      { name: "Kolhapur" },
      { name: "Latur" },
      { name: "Mumbai City" },
      { name: "Mumbai Suburban" },
      { name: "Nagpur" },
      { name: "Nanded" },
      { name: "Nandurbar" },
      { name: "Nashik" },
      { name: "Osmanabad" },
      { name: "Palghar" },
      { name: "Parbhani" },
      { name: "Pune" },
      { name: "Raigad" },
      { name: "Ratnagiri" },
      { name: "Sangli" },
      { name: "Satara" },
      { name: "Sindhudurg" },
      { name: "Solapur" },
      { name: "Thane" },
      { name: "Wardha" },
      { name: "Washim" },
      { name: "Yavatmal" },
    ]
  },
  {
    name: "Manipur",
    nameHi: "मणिपुर",
    nameTe: "మణిపూర్",
    nameTa: "மணிப்பூர்",
    nameKn: "ಮಣಿಪುರ",
    nameMl: "മണിപ്പൂർ",
    nameMr: "मणिपूर",
    nameBn: "মণিপুর",
    nameGu: "મણિપુર",
    nameOr: "ମଣିପୁର",
    namePa: "ਮਨੀਪੁਰ",
    nameUr: "منی پور",
    code: "MN",
    districts: [
      { name: "Bishnupur" },
      { name: "Chandel" },
      { name: "Churachandpur" },
      { name: "Imphal East" },
      { name: "Imphal West" },
      { name: "Jiribam" },
      { name: "Kakching" },
      { name: "Kamjong" },
      { name: "Kangpokpi" },
      { name: "Noney" },
      { name: "Pherzawl" },
      { name: "Senapati" },
      { name: "Tamenglong" },
      { name: "Tengnoupal" },
      { name: "Thoubal" },
      { name: "Ukhrul" },
    ]
  },
  {
    name: "Meghalaya",
    nameHi: "मेघालय",
    nameTe: "మేఘాలయ",
    nameTa: "மேகாலயா",
    nameKn: "ಮೇಘಾಲಯ",
    nameMl: "മേഘാലയ",
    nameMr: "मेघालय",
    nameBn: "মেঘালয়",
    nameGu: "મેઘાલય",
    nameOr: "ମେଘାଳୟ",
    namePa: "ਮੇਘਾਲਿਆ",
    nameUr: "میگھالیہ",
    code: "ML",
    districts: [
      { name: "East Garo Hills" },
      { name: "East Jaintia Hills" },
      { name: "East Khasi Hills" },
      { name: "North Garo Hills" },
      { name: "Ri Bhoi" },
      { name: "South Garo Hills" },
      { name: "South West Garo Hills" },
      { name: "South West Khasi Hills" },
      { name: "West Garo Hills" },
      { name: "West Jaintia Hills" },
      { name: "West Khasi Hills" },
    ]
  },
  {
    name: "Mizoram",
    nameHi: "मिज़ोरम",
    nameTe: "మిజోరం",
    nameTa: "மிசோரம்",
    nameKn: "ಮಿಜೋರಾಂ",
    nameMl: "മിസോറം",
    nameMr: "मिझोरम",
    nameBn: "মিজোরাম",
    nameGu: "મિઝોરમ",
    nameOr: "ମିଜୋରାମ",
    namePa: "ਮਿਜ਼ੋਰਮ",
    nameUr: "میزورم",
    code: "MZ",
    districts: [
      { name: "Aizawl" },
      { name: "Champhai" },
      { name: "Hnahthial" },
      { name: "Khawzawl" },
      { name: "Kolasib" },
      { name: "Lawngtlai" },
      { name: "Lunglei" },
      { name: "Mamit" },
      { name: "Saitual" },
      { name: "Serchhip" },
      { name: "Siaha" },
    ]
  },
  {
    name: "Nagaland",
    nameHi: "नागालैंड",
    nameTe: "నాగాలాండ్",
    nameTa: "நாகாலாந்து",
    nameKn: "ನಾಗಾಲ್ಯಾಂಡ್",
    nameMl: "നാഗാലാൻഡ്",
    nameMr: "नागालँड",
    nameBn: "নাগাল্যান্ড",
    nameGu: "નાગાલેન્ડ",
    nameOr: "ନାଗାଲାଣ୍ଡ",
    namePa: "ਨਾਗਾਲੈਂਡ",
    nameUr: "ناگالینڈ",
    code: "NL",
    districts: [
      { name: "Dimapur" },
      { name: "Kiphire" },
      { name: "Kohima" },
      { name: "Longleng" },
      { name: "Mokokchung" },
      { name: "Mon" },
      { name: "Peren" },
      { name: "Phek" },
      { name: "Tuensang" },
      { name: "Wokha" },
      { name: "Zunheboto" },
    ]
  },
  {
    name: "Odisha",
    nameHi: "ओडिशा",
    nameTe: "ఒడిశా",
    nameOr: "ଓଡ଼ିଶା",
    nameTa: "ஒடிசா",
    nameKn: "ಒಡಿಶಾ",
    nameMl: "ഒഡീഷ",
    nameMr: "ओडिशा",
    nameBn: "ওড়িশা",
    nameGu: "ઓડિશા",
    namePa: "ਓਡੀਸ਼ਾ",
    nameUr: "اوڈیشہ",
    code: "OD",
    districts: [
      { name: "Angul" },
      { name: "Balangir" },
      { name: "Balasore" },
      { name: "Bargarh" },
      { name: "Bhadrak" },
      { name: "Boudh" },
      { name: "Cuttack" },
      { name: "Deogarh" },
      { name: "Dhenkanal" },
      { name: "Gajapati" },
      { name: "Ganjam" },
      { name: "Jagatsinghpur" },
      { name: "Jajpur" },
      { name: "Jharsuguda" },
      { name: "Kalahandi" },
      { name: "Kandhamal" },
      { name: "Kendrapara" },
      { name: "Kendujhar" },
      { name: "Khordha" },
      { name: "Koraput" },
      { name: "Malkangiri" },
      { name: "Mayurbhanj" },
      { name: "Nabarangpur" },
      { name: "Nayagarh" },
      { name: "Nuapada" },
      { name: "Puri" },
      { name: "Rayagada" },
      { name: "Sambalpur" },
      { name: "Subarnapur" },
      { name: "Sundargarh" },
    ]
  },
  {
    name: "Punjab",
    nameHi: "पंजाब",
    nameTe: "పంజాబ్",
    namePa: "ਪੰਜਾਬ",
    nameTa: "பஞ்சாப்",
    nameKn: "ಪಂಜಾಬ್",
    nameMl: "പഞ്ചാബ്",
    nameMr: "पंजाब",
    nameBn: "পাঞ্জাব",
    nameGu: "પંજાબ",
    nameOr: "ପଞ୍ଜାବ",
    nameUr: "پنجاب",
    code: "PB",
    districts: [
      { name: "Amritsar" },
      { name: "Barnala" },
      { name: "Bathinda" },
      { name: "Faridkot" },
      { name: "Fatehgarh Sahib" },
      { name: "Fazilka" },
      { name: "Ferozepur" },
      { name: "Gurdaspur" },
      { name: "Hoshiarpur" },
      { name: "Jalandhar" },
      { name: "Kapurthala" },
      { name: "Ludhiana" },
      { name: "Mansa" },
      { name: "Moga" },
      { name: "Mohali" },
      { name: "Muktsar" },
      { name: "Pathankot" },
      { name: "Patiala" },
      { name: "Rupnagar" },
      { name: "Sangrur" },
      { name: "Shaheed Bhagat Singh Nagar" },
      { name: "Tarn Taran" },
    ]
  },
  {
    name: "Rajasthan",
    nameHi: "राजस्थान",
    nameTe: "రాజస్థాన్",
    nameTa: "ராஜஸ்தான்",
    nameKn: "ರಾಜಸ್ಥಾನ",
    nameMl: "രാജസ്ഥാൻ",
    nameMr: "राजस्थान",
    nameBn: "রাজস্থান",
    nameGu: "રાજસ્થાન",
    nameOr: "ରାଜସ୍ଥାନ",
    namePa: "ਰਾਜਸਥਾਨ",
    nameUr: "راجستھان",
    code: "RJ",
    districts: [
      { name: "Ajmer" },
      { name: "Alwar" },
      { name: "Banswara" },
      { name: "Baran" },
      { name: "Barmer" },
      { name: "Bharatpur" },
      { name: "Bhilwara" },
      { name: "Bikaner" },
      { name: "Bundi" },
      { name: "Chittorgarh" },
      { name: "Churu" },
      { name: "Dausa" },
      { name: "Dholpur" },
      { name: "Dungarpur" },
      { name: "Hanumangarh" },
      { name: "Jaipur" },
      { name: "Jaisalmer" },
      { name: "Jalore" },
      { name: "Jhalawar" },
      { name: "Jhunjhunu" },
      { name: "Jodhpur" },
      { name: "Karauli" },
      { name: "Kota" },
      { name: "Nagaur" },
      { name: "Pali" },
      { name: "Pratapgarh" },
      { name: "Rajsamand" },
      { name: "Sawai Madhopur" },
      { name: "Sikar" },
      { name: "Sirohi" },
      { name: "Sri Ganganagar" },
      { name: "Tonk" },
      { name: "Udaipur" },
    ]
  },
  {
    name: "Sikkim",
    nameHi: "सिक्किम",
    nameTe: "సిక్కిం",
    nameTa: "சிக்கிம்",
    nameKn: "ಸಿಕ್ಕಿಂ",
    nameMl: "സിക്കിം",
    nameMr: "सिक्कीम",
    nameBn: "সিকিম",
    nameGu: "સિક્કિમ",
    nameOr: "ସିକିମ",
    namePa: "ਸਿੱਕਮ",
    nameUr: "سکم",
    code: "SK",
    districts: [
      { name: "East Sikkim" },
      { name: "North Sikkim" },
      { name: "South Sikkim" },
      { name: "West Sikkim" },
    ]
  },
  {
    name: "Tamil Nadu",
    nameHi: "तमिलनाडु",
    nameTe: "తమిళనాడు",
    nameTa: "தமிழ்நாடு",
    nameKn: "ತಮಿಳುನಾಡು",
    nameMl: "തമിഴ്നാട്",
    nameMr: "तमिळनाडू",
    nameBn: "তামিলনাড়ু",
    nameGu: "તમિલનાડુ",
    nameOr: "ତାମିଲନାଡୁ",
    namePa: "ਤਮਿਲਨਾਡੂ",
    nameUr: "تمل ناڈو",
    code: "TN",
    districts: [
      { name: "Ariyalur", nameHi: "अरियालूर", nameTe: "అరియలూర్", nameTa: "அரியலூர்", nameKn: "ಅರಿಯಲೂರ್", nameMl: "അരിയല്ലൂർ" },
      { name: "Chengalpattu", nameHi: "चेंगलपट्टू", nameTe: "చెంగల్పట్టు", nameTa: "செங்கல்பட்டு", nameKn: "ಚೆಂಗಲ್ಪಟ್ಟು", nameMl: "ചെങ്ങൽപട്ട്" },
      { name: "Chennai", nameHi: "चेन्नई", nameTe: "చెన్నై", nameTa: "சென்னை", nameKn: "ಚೆನ್ನೈ", nameMl: "ചെന്നൈ" },
      { name: "Coimbatore", nameHi: "कोयंबटूर", nameTe: "కోయంబత్తూరు", nameTa: "கோயம்புத்தூர்", nameKn: "ಕೊಯಮತ್ತೂರು", nameMl: "കോയമ്പത്തൂർ" },
      { name: "Cuddalore", nameHi: "कुड्डालोर", nameTe: "కడలూరు", nameTa: "கடலூர்", nameKn: "ಕಡಲೂರು", nameMl: "കടലൂർ" },
      { name: "Dharmapuri", nameHi: "धर्मपुरी", nameTe: "ధర్మపురి", nameTa: "தர்மபுரி", nameKn: "ಧರ್ಮಪುರಿ", nameMl: "ധർമ്മപുരി" },
      { name: "Dindigul", nameHi: "डिंडीगुल", nameTe: "దిండిగల్", nameTa: "திண்டுக்கல்", nameKn: "ದಿಂಡಿಗಲ್", nameMl: "ദിണ്ടിഗൽ" },
      { name: "Erode", nameHi: "इरोड", nameTe: "ఈరోడ్", nameTa: "ஈரோடு", nameKn: "ಈರೋಡ್", nameMl: "ഈറോഡ്" },
      { name: "Kallakurichi", nameHi: "कल्लाकुरिची", nameTe: "కళ్ళకురిచి", nameTa: "கள்ளக்குறிச்சி", nameKn: "ಕಲ್ಲಕುರಿಚಿ", nameMl: "കള്ളക്കുറിച്ചി" },
      { name: "Kancheepuram", nameHi: "कांचीपुरम", nameTe: "కాంచీపురం", nameTa: "காஞ்சிபுரம்", nameKn: "ಕಾಂಚಿಪುರಂ", nameMl: "കാഞ്ചീപുരം" },
      { name: "Karur", nameHi: "करूर", nameTe: "కరూర్", nameTa: "கரூர்", nameKn: "ಕರೂರ್", nameMl: "കരൂർ" },
      { name: "Krishnagiri", nameHi: "कृष्णागिरी", nameTe: "కృష్ణగిరి", nameTa: "கிருஷ்ணகிரி", nameKn: "ಕೃಷ್ಣಗಿರಿ", nameMl: "കൃഷ്ണഗിരി" },
      { name: "Madurai", nameHi: "मदुरै", nameTe: "మదురై", nameTa: "மதுரை", nameKn: "ಮಧುರೆ", nameMl: "മധുര" },
      { name: "Nagapattinam", nameHi: "नागापट्टिनम", nameTe: "నాగపట్నం", nameTa: "நாகப்பட்டினம்", nameKn: "ನಾಗಪಟ್ಟಣಂ", nameMl: "നാഗപട്ടണം" },
      { name: "Namakkal", nameHi: "नमक्कल", nameTe: "నమక్కల్", nameTa: "நாமக்கல்", nameKn: "ನಾಮಕ್ಕಲ್", nameMl: "നാമക്കൽ" },
      { name: "Nilgiris", nameHi: "नीलगिरी", nameTe: "నీలగిరి", nameTa: "நீலகிரி", nameKn: "ನೀಲಗಿರಿ", nameMl: "നീലഗിരി" },
      { name: "Perambalur", nameHi: "पेरम्बलूर", nameTe: "పెరంబలూర్", nameTa: "பெரம்பலூர்", nameKn: "ಪೆರಂಬಲೂರ್", nameMl: "പെരമ്പല്ലൂർ" },
      { name: "Pudukkottai", nameHi: "पुदुकोट्टई", nameTe: "పుదుక్కోట్టై", nameTa: "புதுக்கோட்டை", nameKn: "ಪುದುಕ್ಕೊಟ್ಟೈ", nameMl: "പുതുക്കോട്ട" },
      { name: "Ramanathapuram", nameHi: "रामनाथपुरम", nameTe: "రామనాథపురం", nameTa: "ராமநாதபுரம்", nameKn: "ರಾಮನಾಥಪುರಂ", nameMl: "രാമനാഥപുരം" },
      { name: "Ranipet", nameHi: "रानीपेट", nameTe: "రాణిపేట", nameTa: "ராணிப்பேட்டை", nameKn: "ರಾಣಿಪೇಟೆ", nameMl: "റാണിപ്പേട്ട" },
      { name: "Salem", nameHi: "सेलम", nameTe: "సేలం", nameTa: "சேலம்", nameKn: "ಸೇಲಂ", nameMl: "സേലം" },
      { name: "Sivaganga", nameHi: "शिवगंगा", nameTe: "శివగంగ", nameTa: "சிவகங்கை", nameKn: "ಶಿವಗಂಗಾ", nameMl: "ശിവഗംഗ" },
      { name: "Tenkasi", nameHi: "तेनकासी", nameTe: "తెన్కాసి", nameTa: "தென்காசி", nameKn: "ತೆನ್ಕಾಸಿ", nameMl: "തെങ്കാശി" },
      { name: "Thanjavur", nameHi: "तंजावुर", nameTe: "తంజావూరు", nameTa: "தஞ்சாவூர்", nameKn: "ತಂಜಾವೂರು", nameMl: "തഞ്ചാവൂർ" },
      { name: "Theni", nameHi: "थेनी", nameTe: "తేని", nameTa: "தேனி", nameKn: "ಥೇಣಿ", nameMl: "തേനി" },
      { name: "Thoothukudi", nameHi: "थूथुकुडी", nameTe: "తూత్తుకుడి", nameTa: "தூத்துக்குடி", nameKn: "ತೂತುಕುಡಿ", nameMl: "തൂത്തുക്കുടി" },
      { name: "Tiruchirappalli", nameHi: "तिरुच्चिरापल्ली", nameTe: "తిరుచిరాపల్లి", nameTa: "திருச்சிராப்பள்ளி", nameKn: "ತಿರುಚಿರಾಪಳ್ಳಿ", nameMl: "തിരുച്ചിറപ്പള്ളി" },
      { name: "Tirunelveli", nameHi: "तिरुनेलवेली", nameTe: "తిరునెల్వేలి", nameTa: "திருநெல்வேலி", nameKn: "ತಿರುನೆಲ್ವೇಲಿ", nameMl: "തിരുനെൽവേലി" },
      { name: "Tirupathur", nameHi: "तिरुपात्तूर", nameTe: "తిరుపత్తూరు", nameTa: "திருப்பத்தூர்", nameKn: "ತಿರುಪತ್ತೂರು", nameMl: "തിരുപ്പത്തൂർ" },
      { name: "Tiruppur", nameHi: "तिरुप्पुर", nameTe: "తిరుపూర్", nameTa: "திருப்பூர்", nameKn: "ತಿರುಪ್ಪುರ್", nameMl: "തിരുപ്പൂർ" },
      { name: "Tiruvallur", nameHi: "तिरुवल्लूर", nameTe: "తిరువళ్లూరు", nameTa: "திருவள்ளூர்", nameKn: "ತಿರುವಳ್ಳೂರು", nameMl: "തിരുവള്ളൂർ" },
      { name: "Tiruvannamalai", nameHi: "तिरुवन्नामलई", nameTe: "తిరువణ్ణామలై", nameTa: "திருவண்ணாமலை", nameKn: "ತಿರುವಣ್ಣಾಮಲೈ", nameMl: "തിരുവണ്ണാമലൈ" },
      { name: "Tiruvarur", nameHi: "तिरुवारुर", nameTe: "తిరువారూరు", nameTa: "திருவாரூர்", nameKn: "ತಿರುವಾರೂರು", nameMl: "തിരുവാരൂർ" },
      { name: "Vellore", nameHi: "वेल्लोर", nameTe: "వెల్లూరు", nameTa: "வேலூர்", nameKn: "ವೇಲೂರು", nameMl: "വേലൂർ" },
      { name: "Viluppuram", nameHi: "विलुप्पुरम", nameTe: "విల్లుపురం", nameTa: "விழுப்புரம்", nameKn: "ವಿಲ್ಲುಪುರಂ", nameMl: "വിഴുപ്പുറം" },
      { name: "Virudhunagar", nameHi: "विरुधुनगर", nameTe: "విరుదునగర్", nameTa: "விருதுநகர்", nameKn: "ವಿರುದುನಗರ್", nameMl: "വിരുദുനഗർ" },
    ]
  },
  {
    name: "Telangana",
    nameHi: "तेलंगाना",
    nameTe: "తెలంగాణ",
    nameTa: "தெலுங்கானா",
    nameKn: "ತೆಲಂಗಾಣ",
    nameMl: "തെലങ്കാന",
    nameMr: "तेलंगणा",
    nameBn: "তেলেঙ্গানা",
    nameGu: "તેલંગાણા",
    nameOr: "ତେଲେଙ୍ଗାନା",
    namePa: "ਤੇਲੰਗਾਨਾ",
    nameUr: "تلنگانہ",
    code: "TG",
    districts: [
      { name: "Adilabad" },
      { name: "Bhadradri Kothagudem" },
      { name: "Hyderabad" },
      { name: "Jagtial" },
      { name: "Jangaon" },
      { name: "Jayashankar Bhupalpally" },
      { name: "Jogulamba Gadwal" },
      { name: "Kamareddy" },
      { name: "Karimnagar" },
      { name: "Khammam" },
      { name: "Komaram Bheem Asifabad" },
      { name: "Mahabubabad" },
      { name: "Mahabubnagar" },
      { name: "Mancherial" },
      { name: "Medak" },
      { name: "Medchal-Malkajgiri" },
      { name: "Mulugu" },
      { name: "Nagarkurnool" },
      { name: "Nalgonda" },
      { name: "Narayanpet" },
      { name: "Nirmal" },
      { name: "Nizamabad" },
      { name: "Peddapalli" },
      { name: "Rajanna Sircilla" },
      { name: "Rangareddy" },
      { name: "Sangareddy" },
      { name: "Siddipet" },
      { name: "Suryapet" },
      { name: "Vikarabad" },
      { name: "Wanaparthy" },
      { name: "Warangal Rural" },
      { name: "Warangal Urban" },
      { name: "Yadadri Bhuvanagiri" },
    ]
  },
  {
    name: "Tripura",
    nameHi: "त्रिपुरा",
    nameTe: "త్రిపుర",
    nameTa: "திரிபுரா",
    nameKn: "ತ್ರಿಪುರ",
    nameMl: "ത്രിപുര",
    nameMr: "त्रिपुरा",
    nameBn: "ত্রিপুরা",
    nameGu: "ત્રિપુરા",
    nameOr: "ତ୍ରିପୁରା",
    namePa: "ਤ੍ਰਿਪੁਰਾ",
    nameUr: "تریپورہ",
    code: "TR",
    districts: [
      { name: "Dhalai" },
      { name: "Gomati" },
      { name: "Khowai" },
      { name: "North Tripura" },
      { name: "Sepahijala" },
      { name: "South Tripura" },
      { name: "Unakoti" },
      { name: "West Tripura" },
    ]
  },
  {
    name: "Uttar Pradesh",
    nameHi: "उत्तर प्रदेश",
    nameTe: "ఉత్తర ప్రదేశ్",
    nameTa: "உத்தரப் பிரதேசம்",
    nameKn: "ಉತ್ತರ ಪ್ರದೇಶ",
    nameMl: "ഉത്തർപ്രദേശ്",
    nameMr: "उत्तर प्रदेश",
    nameBn: "উত্তরপ্রদেশ",
    nameGu: "ઉત્તર પ્રદેશ",
    nameOr: "ଉତ୍ତର ପ୍ରଦେଶ",
    namePa: "ਉੱਤਰ ਪ੍ਰਦੇਸ਼",
    nameUr: "اتر پردیش",
    code: "UP",
    districts: [
      { name: "Agra" },
      { name: "Aligarh" },
      { name: "Ambedkar Nagar" },
      { name: "Amethi" },
      { name: "Amroha" },
      { name: "Auraiya" },
      { name: "Ayodhya" },
      { name: "Azamgarh" },
      { name: "Baghpat" },
      { name: "Bahraich" },
      { name: "Ballia" },
      { name: "Balrampur" },
      { name: "Banda" },
      { name: "Barabanki" },
      { name: "Bareilly" },
      { name: "Basti" },
      { name: "Bhadohi" },
      { name: "Bijnor" },
      { name: "Budaun" },
      { name: "Bulandshahr" },
      { name: "Chandauli" },
      { name: "Chitrakoot" },
      { name: "Deoria" },
      { name: "Etah" },
      { name: "Etawah" },
      { name: "Farrukhabad" },
      { name: "Fatehpur" },
      { name: "Firozabad" },
      { name: "Gautam Buddha Nagar" },
      { name: "Ghaziabad" },
      { name: "Ghazipur" },
      { name: "Gonda" },
      { name: "Gorakhpur" },
      { name: "Hamirpur" },
      { name: "Hapur" },
      { name: "Hardoi" },
      { name: "Hathras" },
      { name: "Jalaun" },
      { name: "Jaunpur" },
      { name: "Jhansi" },
      { name: "Kannauj" },
      { name: "Kanpur Dehat" },
      { name: "Kanpur Nagar" },
      { name: "Kasganj" },
      { name: "Kaushambi" },
      { name: "Kushinagar" },
      { name: "Lakhimpur Kheri" },
      { name: "Lalitpur" },
      { name: "Lucknow" },
      { name: "Maharajganj" },
      { name: "Mahoba" },
      { name: "Mainpuri" },
      { name: "Mathura" },
      { name: "Mau" },
      { name: "Meerut" },
      { name: "Mirzapur" },
      { name: "Moradabad" },
      { name: "Muzaffarnagar" },
      { name: "Pilibhit" },
      { name: "Pratapgarh" },
      { name: "Prayagraj" },
      { name: "Rae Bareli" },
      { name: "Rampur" },
      { name: "Saharanpur" },
      { name: "Sambhal" },
      { name: "Sant Kabir Nagar" },
      { name: "Shahjahanpur" },
      { name: "Shamli" },
      { name: "Shrawasti" },
      { name: "Siddharthnagar" },
      { name: "Sitapur" },
      { name: "Sonbhadra" },
      { name: "Sultanpur" },
      { name: "Unnao" },
      { name: "Varanasi" },
    ]
  },
  {
    name: "Uttarakhand",
    nameHi: "उत्तराखंड",
    nameTe: "ఉత్తరాఖండ్",
    nameTa: "உத்தரகண்ட்",
    nameKn: "ಉತ್ತರಾಖಂಡ",
    nameMl: "ഉത്തരാഖണ്ഡ്",
    nameMr: "उत्तराखंड",
    nameBn: "উত্তরাখণ্ড",
    nameGu: "ઉત્તરાખંડ",
    nameOr: "ଉତ୍ତରାଖଣ୍ଡ",
    namePa: "ਉਤਰਾਖੰਡ",
    nameUr: "اتراکھنڈ",
    code: "UK",
    districts: [
      { name: "Almora" },
      { name: "Bageshwar" },
      { name: "Chamoli" },
      { name: "Champawat" },
      { name: "Dehradun" },
      { name: "Haridwar" },
      { name: "Nainital" },
      { name: "Pauri Garhwal" },
      { name: "Pithoragarh" },
      { name: "Rudraprayag" },
      { name: "Tehri Garhwal" },
      { name: "Udham Singh Nagar" },
      { name: "Uttarkashi" },
    ]
  },
  {
    name: "West Bengal",
    nameHi: "पश्चिम बंगाल",
    nameTe: "పశ్చిమ బెంగాల్",
    nameBn: "পশ্চিমবঙ্গ",
    nameTa: "மேற்கு வங்கம்",
    nameKn: "ಪಶ್ಚಿಮ ಬಂಗಾಳ",
    nameMl: "പശ്ചിമ ബംഗാൾ",
    nameMr: "पश्चिम बंगाल",
    nameGu: "પશ્ચિમ બંગાળ",
    nameOr: "ପଶ୍ଚିମବଙ୍ଗ",
    namePa: "ਪੱਛਮੀ ਬੰਗਾਲ",
    nameUr: "مغربی بنگال",
    code: "WB",
    districts: [
      { name: "Alipurduar" },
      { name: "Bankura" },
      { name: "Birbhum" },
      { name: "Cooch Behar" },
      { name: "Dakshin Dinajpur" },
      { name: "Darjeeling" },
      { name: "Hooghly" },
      { name: "Howrah" },
      { name: "Jalpaiguri" },
      { name: "Jhargram" },
      { name: "Kalimpong" },
      { name: "Kolkata" },
      { name: "Malda" },
      { name: "Murshidabad" },
      { name: "Nadia" },
      { name: "North 24 Parganas" },
      { name: "Paschim Bardhaman" },
      { name: "Paschim Medinipur" },
      { name: "Purba Bardhaman" },
      { name: "Purba Medinipur" },
      { name: "Purulia" },
      { name: "South 24 Parganas" },
      { name: "Uttar Dinajpur" },
    ]
  },
  // Union Territories
  {
    name: "Andaman and Nicobar Islands",
    nameHi: "अंडमान और निकोबार द्वीप समूह",
    nameTe: "అండమాన్ నికోబార్ దీవులు",
    nameTa: "அந்தமான் மற்றும் நிக்கோபார் தீவுகள்",
    nameKn: "ಅಂಡಮಾನ್ ಮತ್ತು ನിക്കೋಬಾರ್ ದ್ವೀಪಗಳು",
    nameMl: "ആന്തമാൻ നിക്കോബാർ ദ്വീപുകൾ",
    nameMr: "अंदमान आणि निकोबार बेटे",
    nameBn: "আন্দামান ও নিকোবর দ্বীপপুঞ্জ",
    nameGu: "અંદામાન અને નિકોબાર ટાપુઓ",
    nameOr: "ଆଣ୍ଡାମାନ ଏବଂ ନିକୋବର ଦ୍ୱୀପପୁଞ୍ଜ",
    namePa: "ਅੰਡੇਮਾਨ ਅਤੇ ਨିକੋਬਾਰ ਟਾਪੂ",
    nameUr: "انڈمان اور نکوبار جزائر",
    code: "AN",
    districts: [
      { name: "Nicobar" },
      { name: "North and Middle Andaman" },
      { name: "South Andaman" },
    ]
  },
  {
    name: "Chandigarh",
    nameHi: "चंडीगढ़",
    nameTe: "చండీగఢ్",
    nameTa: "சண்டிகர்",
    nameKn: "ಚಂಡೀಗಢ",
    nameMl: "ചണ്ഡീഗഢ്",
    nameMr: "चंदीगड",
    nameBn: "চণ্ডীগড়",
    nameGu: "ચંદીગઢ",
    nameOr: "ଚଣ୍ଡୀଗଡ଼",
    namePa: "ਚੰਡੀਗੜ੍ਹ",
    nameUr: "چنڈی گڑھ",
    code: "CH",
    districts: [
      { name: "Chandigarh" },
    ]
  },
  {
    name: "Dadra and Nagar Haveli and Daman and Diu",
    nameHi: "दादरा और नगर हवेली और दमन और दीव",
    nameTe: "దాద్రా నగర్ హవేలీ దమన్ డయ్యూ",
    nameTa: "தாத்ரா மற்றும் நகர் ஹவேலி மற்றும் டாமன் மற்றும் டியூ",
    nameKn: "ದಾದ್ರಾ ಮತ್ತು ನಗರ ಹವೇಲಿ ಮತ್ತು ದಮನ್ ಮತ್ತು ದಿಯು",
    nameMl: "ദാദ്ര നഗർ ഹവേലി ദാമൻ ദിയു",
    nameMr: "दादरा आणि नगर हवेली आणि दमण आणि दीव",
    nameBn: "দাদরা ও নগর হাভেলি এবং দামান ও দিউ",
    nameGu: "દાદરા અને નગર હવેલી અને દમણ અને દીવ",
    nameOr: "ଦାଦ୍ରା ଏବଂ ନଗର ହାଭେଲି ଏବଂ ଦାମନ ଏବଂ ଦିଉ",
    namePa: "ਦਾਦਰਾ ਅਤੇ ਨਗਰ ਹਵੇਲੀ ਅਤੇ ਦਮਨ ਅਤੇ ਦੀਉ",
    nameUr: "دادرا و نگر حویلی اور دمن و دیو",
    code: "DD",
    districts: [
      { name: "Dadra and Nagar Haveli" },
      { name: "Daman" },
      { name: "Diu" },
    ]
  },
  {
    name: "Jammu and Kashmir",
    nameHi: "जम्मू और कश्मीर",
    nameTe: "జమ్ము కాశ్మీర్",
    nameTa: "ஜம்மு மற்றும் காஷ்மீர்",
    nameKn: "ಜಮ್ಮು ಮತ್ತು ಕಾಶ್ಮೀರ",
    nameMl: "ജമ്മു കശ്മീർ",
    nameMr: "जम्मू आणि काश्मीर",
    nameBn: "জম্মু ও কাশ্মীর",
    nameGu: "જમ્મુ અને કાશ્મીર",
    nameOr: "ଜମ୍ମୁ ଏବଂ କାଶ୍ମୀର",
    namePa: "ਜੰਮੂ ਅਤੇ ਕਸ਼ਮੀਰ",
    nameUr: "جموں و کشمیر",
    code: "JK",
    districts: [
      { name: "Anantnag" },
      { name: "Bandipora" },
      { name: "Baramulla" },
      { name: "Budgam" },
      { name: "Doda" },
      { name: "Ganderbal" },
      { name: "Jammu" },
      { name: "Kathua" },
      { name: "Kishtwar" },
      { name: "Kulgam" },
      { name: "Kupwara" },
      { name: "Poonch" },
      { name: "Pulwama" },
      { name: "Rajouri" },
      { name: "Ramban" },
      { name: "Reasi" },
      { name: "Samba" },
      { name: "Shopian" },
      { name: "Srinagar" },
      { name: "Udhampur" },
    ]
  },
  {
    name: "Ladakh",
    nameHi: "लद्दाख",
    nameTe: "లడఖ్",
    nameTa: "லடாக்",
    nameKn: "ಲಡಾಖ್",
    nameMl: "ലഡാക്ക്",
    nameMr: "लडाख",
    nameBn: "লাদাখ",
    nameGu: "લદ્દાખ",
    nameOr: "ଲଦାଖ",
    namePa: "ਲਦਾਖ",
    nameUr: "لداخ",
    code: "LA",
    districts: [
      { name: "Kargil" },
      { name: "Leh" },
    ]
  },
  {
    name: "Lakshadweep",
    nameHi: "लक्षद्वीप",
    nameTe: "లక్షద్వీప",
    nameTa: "லட்சத்தீவு",
    nameKn: "ಲಕ್ಷದ್ವೀಪ",
    nameMl: "ലക്ഷദ്വീപ്",
    nameMr: "लक्षद्वीप",
    nameBn: "লাক্ষাদ্বীপ",
    nameGu: "લક્ષદ્વીપ",
    nameOr: "ଲାକ୍ଷାଦ୍ୱୀପ",
    namePa: "ਲਕਸ਼ਦੀਪ",
    nameUr: "لکشدیپ",
    code: "LD",
    districts: [
      { name: "Lakshadweep" },
    ]
  },
  {
    name: "Puducherry",
    nameHi: "पुदुचेरी",
    nameTe: "పుదుచ్చేరి",
    nameTa: "புதுச்சேரி",
    nameKn: "ಪುದುಚೇರಿ",
    nameMl: "പുതുച്ചേരി",
    nameMr: "पुद्दुचेरी",
    nameBn: "পুদুচেরি",
    nameGu: "પુડુચેરી",
    nameOr: "ପୁଡୁଚେରୀ",
    namePa: "ਪੁਡੂਚੇਰੀ",
    nameUr: "پدوچیری",
    code: "PY",
    districts: [
      { name: "Karaikal" },
      { name: "Mahe" },
      { name: "Puducherry" },
      { name: "Yanam" },
    ]
  },
];

// Helper function to get state by code
export function getStateByCode(code: string): State | undefined {
  return INDIAN_STATES.find(s => s.code === code);
}

// Helper function to get state by name
export function getStateByName(name: string): State | undefined {
  return INDIAN_STATES.find(s => s.name.toLowerCase() === name.toLowerCase());
}

// Helper function to get districts for a state
export function getDistrictsForState(stateCodeOrName: string): District[] {
  const state = getStateByCode(stateCodeOrName) || getStateByName(stateCodeOrName);
  return state?.districts || [];
}
