// Indian States and Districts Data

export interface District {
  name: string;
  nameHi?: string;
  nameTe?: string;
}

export interface State {
  name: string;
  nameHi: string;
  nameTe: string;
  code: string;
  districts: District[];
}

export const INDIAN_STATES: State[] = [
  {
    name: "Andhra Pradesh",
    nameHi: "आंध्र प्रदेश",
    nameTe: "ఆంధ్ర ప్రదేశ్",
    code: "AP",
    districts: [
      { name: "Anantapur", nameHi: "अनंतपुर", nameTe: "అనంతపురం" },
      { name: "Chittoor", nameHi: "चित्तूर", nameTe: "చిత్తూరు" },
      { name: "East Godavari", nameHi: "पूर्व गोदावरी", nameTe: "తూర్పు గోదావరి" },
      { name: "Guntur", nameHi: "गुंटूर", nameTe: "గుంటూరు" },
      { name: "Kadapa", nameHi: "कडप्पा", nameTe: "కడప" },
      { name: "Krishna", nameHi: "कृष्णा", nameTe: "కృష్ణా" },
      { name: "Kurnool", nameHi: "कुर्नूल", nameTe: "కర్నూలు" },
      { name: "Nellore", nameHi: "नेल्लोर", nameTe: "నెల్లూరు" },
      { name: "Prakasam", nameHi: "प्रकाशम", nameTe: "ప్రకాశం" },
      { name: "Srikakulam", nameHi: "श्रीकाकुलम", nameTe: "శ్రీకాకుళం" },
      { name: "Visakhapatnam", nameHi: "विशाखापट्टनम", nameTe: "విశాఖపట్నం" },
      { name: "Vizianagaram", nameHi: "विजयनगरम", nameTe: "విజయనగరం" },
      { name: "West Godavari", nameHi: "पश्चिम गोदावरी", nameTe: "పశ్చిమ గోదావరి" },
    ]
  },
  {
    name: "Arunachal Pradesh",
    nameHi: "अरुणाचल प्रदेश",
    nameTe: "అరుణాచల్ ప్రదేశ్",
    code: "AR",
    districts: [
      { name: "Anjaw" },
      { name: "Changlang" },
      { name: "Dibang Valley" },
      { name: "East Kameng" },
      { name: "East Siang" },
      { name: "Itanagar Capital Complex" },
      { name: "Kurung Kumey" },
      { name: "Lohit" },
      { name: "Lower Dibang Valley" },
      { name: "Lower Subansiri" },
      { name: "Papum Pare" },
      { name: "Tawang" },
      { name: "Tirap" },
      { name: "Upper Siang" },
      { name: "Upper Subansiri" },
      { name: "West Kameng" },
      { name: "West Siang" },
    ]
  },
  {
    name: "Assam",
    nameHi: "असम",
    nameTe: "అస్సాం",
    code: "AS",
    districts: [
      { name: "Baksa" },
      { name: "Barpeta" },
      { name: "Biswanath" },
      { name: "Bongaigaon" },
      { name: "Cachar" },
      { name: "Charaideo" },
      { name: "Chirang" },
      { name: "Darrang" },
      { name: "Dhemaji" },
      { name: "Dhubri" },
      { name: "Dibrugarh" },
      { name: "Goalpara" },
      { name: "Golaghat" },
      { name: "Guwahati" },
      { name: "Hailakandi" },
      { name: "Jorhat" },
      { name: "Kamrup" },
      { name: "Karbi Anglong" },
      { name: "Karimganj" },
      { name: "Kokrajhar" },
      { name: "Lakhimpur" },
      { name: "Majuli" },
      { name: "Morigaon" },
      { name: "Nagaon" },
      { name: "Nalbari" },
      { name: "Sivasagar" },
      { name: "Sonitpur" },
      { name: "Tinsukia" },
      { name: "Udalguri" },
    ]
  },
  {
    name: "Bihar",
    nameHi: "बिहार",
    nameTe: "బీహార్",
    code: "BR",
    districts: [
      { name: "Araria" },
      { name: "Arwal" },
      { name: "Aurangabad" },
      { name: "Banka" },
      { name: "Begusarai" },
      { name: "Bhagalpur" },
      { name: "Bhojpur" },
      { name: "Buxar" },
      { name: "Darbhanga" },
      { name: "East Champaran" },
      { name: "Gaya" },
      { name: "Gopalganj" },
      { name: "Jamui" },
      { name: "Jehanabad" },
      { name: "Kaimur" },
      { name: "Katihar" },
      { name: "Khagaria" },
      { name: "Kishanganj" },
      { name: "Lakhisarai" },
      { name: "Madhepura" },
      { name: "Madhubani" },
      { name: "Munger" },
      { name: "Muzaffarpur" },
      { name: "Nalanda" },
      { name: "Nawada" },
      { name: "Patna" },
      { name: "Purnia" },
      { name: "Rohtas" },
      { name: "Saharsa" },
      { name: "Samastipur" },
      { name: "Saran" },
      { name: "Sheikhpura" },
      { name: "Sheohar" },
      { name: "Sitamarhi" },
      { name: "Siwan" },
      { name: "Supaul" },
      { name: "Vaishali" },
      { name: "West Champaran" },
    ]
  },
  {
    name: "Chhattisgarh",
    nameHi: "छत्तीसगढ़",
    nameTe: "ఛత్తీస్‌గఢ్",
    code: "CG",
    districts: [
      { name: "Balod" },
      { name: "Baloda Bazar" },
      { name: "Balrampur" },
      { name: "Bastar" },
      { name: "Bemetara" },
      { name: "Bijapur" },
      { name: "Bilaspur" },
      { name: "Dantewada" },
      { name: "Dhamtari" },
      { name: "Durg" },
      { name: "Gariaband" },
      { name: "Janjgir-Champa" },
      { name: "Jashpur" },
      { name: "Kabirdham" },
      { name: "Kanker" },
      { name: "Kondagaon" },
      { name: "Korba" },
      { name: "Koriya" },
      { name: "Mahasamund" },
      { name: "Mungeli" },
      { name: "Narayanpur" },
      { name: "Raigarh" },
      { name: "Raipur" },
      { name: "Rajnandgaon" },
      { name: "Sukma" },
      { name: "Surajpur" },
      { name: "Surguja" },
    ]
  },
  {
    name: "Delhi",
    nameHi: "दिल्ली",
    nameTe: "ఢిల్లీ",
    code: "DL",
    districts: [
      { name: "Central Delhi" },
      { name: "East Delhi" },
      { name: "New Delhi" },
      { name: "North Delhi" },
      { name: "North East Delhi" },
      { name: "North West Delhi" },
      { name: "Shahdara" },
      { name: "South Delhi" },
      { name: "South East Delhi" },
      { name: "South West Delhi" },
      { name: "West Delhi" },
    ]
  },
  {
    name: "Goa",
    nameHi: "गोवा",
    nameTe: "గోవా",
    code: "GA",
    districts: [
      { name: "North Goa" },
      { name: "South Goa" },
    ]
  },
  {
    name: "Gujarat",
    nameHi: "गुजरात",
    nameTe: "గుజరాత్",
    code: "GJ",
    districts: [
      { name: "Ahmedabad" },
      { name: "Amreli" },
      { name: "Anand" },
      { name: "Aravalli" },
      { name: "Banaskantha" },
      { name: "Bharuch" },
      { name: "Bhavnagar" },
      { name: "Botad" },
      { name: "Chhota Udaipur" },
      { name: "Dahod" },
      { name: "Dang" },
      { name: "Devbhoomi Dwarka" },
      { name: "Gandhinagar" },
      { name: "Gir Somnath" },
      { name: "Jamnagar" },
      { name: "Junagadh" },
      { name: "Kheda" },
      { name: "Kutch" },
      { name: "Mahisagar" },
      { name: "Mehsana" },
      { name: "Morbi" },
      { name: "Narmada" },
      { name: "Navsari" },
      { name: "Panchmahal" },
      { name: "Patan" },
      { name: "Porbandar" },
      { name: "Rajkot" },
      { name: "Sabarkantha" },
      { name: "Surat" },
      { name: "Surendranagar" },
      { name: "Tapi" },
      { name: "Vadodara" },
      { name: "Valsad" },
    ]
  },
  {
    name: "Haryana",
    nameHi: "हरियाणा",
    nameTe: "హర్యానా",
    code: "HR",
    districts: [
      { name: "Ambala" },
      { name: "Bhiwani" },
      { name: "Charkhi Dadri" },
      { name: "Faridabad" },
      { name: "Fatehabad" },
      { name: "Gurugram" },
      { name: "Hisar" },
      { name: "Jhajjar" },
      { name: "Jind" },
      { name: "Kaithal" },
      { name: "Karnal" },
      { name: "Kurukshetra" },
      { name: "Mahendragarh" },
      { name: "Nuh" },
      { name: "Palwal" },
      { name: "Panchkula" },
      { name: "Panipat" },
      { name: "Rewari" },
      { name: "Rohtak" },
      { name: "Sirsa" },
      { name: "Sonipat" },
      { name: "Yamunanagar" },
    ]
  },
  {
    name: "Himachal Pradesh",
    nameHi: "हिमाचल प्रदेश",
    nameTe: "హిమాచల్ ప్రదేశ్",
    code: "HP",
    districts: [
      { name: "Bilaspur" },
      { name: "Chamba" },
      { name: "Hamirpur" },
      { name: "Kangra" },
      { name: "Kinnaur" },
      { name: "Kullu" },
      { name: "Lahaul and Spiti" },
      { name: "Mandi" },
      { name: "Shimla" },
      { name: "Sirmaur" },
      { name: "Solan" },
      { name: "Una" },
    ]
  },
  {
    name: "Jharkhand",
    nameHi: "झारखंड",
    nameTe: "జార్ఖండ్",
    code: "JH",
    districts: [
      { name: "Bokaro" },
      { name: "Chatra" },
      { name: "Deoghar" },
      { name: "Dhanbad" },
      { name: "Dumka" },
      { name: "East Singhbhum" },
      { name: "Garhwa" },
      { name: "Giridih" },
      { name: "Godda" },
      { name: "Gumla" },
      { name: "Hazaribagh" },
      { name: "Jamtara" },
      { name: "Khunti" },
      { name: "Koderma" },
      { name: "Latehar" },
      { name: "Lohardaga" },
      { name: "Pakur" },
      { name: "Palamu" },
      { name: "Ramgarh" },
      { name: "Ranchi" },
      { name: "Sahebganj" },
      { name: "Seraikela Kharsawan" },
      { name: "Simdega" },
      { name: "West Singhbhum" },
    ]
  },
  {
    name: "Karnataka",
    nameHi: "कर्नाटक",
    nameTe: "కర్ణాటక",
    code: "KA",
    districts: [
      { name: "Bagalkot" },
      { name: "Ballari" },
      { name: "Belagavi" },
      { name: "Bengaluru Rural" },
      { name: "Bengaluru Urban" },
      { name: "Bidar" },
      { name: "Chamarajanagar" },
      { name: "Chikballapur" },
      { name: "Chikkamagaluru" },
      { name: "Chitradurga" },
      { name: "Dakshina Kannada" },
      { name: "Davanagere" },
      { name: "Dharwad" },
      { name: "Gadag" },
      { name: "Hassan" },
      { name: "Haveri" },
      { name: "Kalaburagi" },
      { name: "Kodagu" },
      { name: "Kolar" },
      { name: "Koppal" },
      { name: "Mandya" },
      { name: "Mysuru" },
      { name: "Raichur" },
      { name: "Ramanagara" },
      { name: "Shivamogga" },
      { name: "Tumakuru" },
      { name: "Udupi" },
      { name: "Uttara Kannada" },
      { name: "Vijayapura" },
      { name: "Yadgir" },
    ]
  },
  {
    name: "Kerala",
    nameHi: "केरल",
    nameTe: "కేరళ",
    code: "KL",
    districts: [
      { name: "Alappuzha" },
      { name: "Ernakulam" },
      { name: "Idukki" },
      { name: "Kannur" },
      { name: "Kasaragod" },
      { name: "Kollam" },
      { name: "Kottayam" },
      { name: "Kozhikode" },
      { name: "Malappuram" },
      { name: "Palakkad" },
      { name: "Pathanamthitta" },
      { name: "Thiruvananthapuram" },
      { name: "Thrissur" },
      { name: "Wayanad" },
    ]
  },
  {
    name: "Madhya Pradesh",
    nameHi: "मध्य प्रदेश",
    nameTe: "మధ్య ప్రదేశ్",
    code: "MP",
    districts: [
      { name: "Agar Malwa" },
      { name: "Alirajpur" },
      { name: "Anuppur" },
      { name: "Ashoknagar" },
      { name: "Balaghat" },
      { name: "Barwani" },
      { name: "Betul" },
      { name: "Bhind" },
      { name: "Bhopal" },
      { name: "Burhanpur" },
      { name: "Chhatarpur" },
      { name: "Chhindwara" },
      { name: "Damoh" },
      { name: "Datia" },
      { name: "Dewas" },
      { name: "Dhar" },
      { name: "Dindori" },
      { name: "Guna" },
      { name: "Gwalior" },
      { name: "Harda" },
      { name: "Hoshangabad" },
      { name: "Indore" },
      { name: "Jabalpur" },
      { name: "Jhabua" },
      { name: "Katni" },
      { name: "Khandwa" },
      { name: "Khargone" },
      { name: "Mandla" },
      { name: "Mandsaur" },
      { name: "Morena" },
      { name: "Narsinghpur" },
      { name: "Neemuch" },
      { name: "Panna" },
      { name: "Raisen" },
      { name: "Rajgarh" },
      { name: "Ratlam" },
      { name: "Rewa" },
      { name: "Sagar" },
      { name: "Satna" },
      { name: "Sehore" },
      { name: "Seoni" },
      { name: "Shahdol" },
      { name: "Shajapur" },
      { name: "Sheopur" },
      { name: "Shivpuri" },
      { name: "Sidhi" },
      { name: "Singrauli" },
      { name: "Tikamgarh" },
      { name: "Ujjain" },
      { name: "Umaria" },
      { name: "Vidisha" },
    ]
  },
  {
    name: "Maharashtra",
    nameHi: "महाराष्ट्र",
    nameTe: "మహారాష్ట్ర",
    code: "MH",
    districts: [
      { name: "Ahmednagar" },
      { name: "Akola" },
      { name: "Amravati" },
      { name: "Aurangabad" },
      { name: "Beed" },
      { name: "Bhandara" },
      { name: "Buldhana" },
      { name: "Chandrapur" },
      { name: "Dhule" },
      { name: "Gadchiroli" },
      { name: "Gondia" },
      { name: "Hingoli" },
      { name: "Jalgaon" },
      { name: "Jalna" },
      { name: "Kolhapur" },
      { name: "Latur" },
      { name: "Mumbai City" },
      { name: "Mumbai Suburban" },
      { name: "Nagpur" },
      { name: "Nanded" },
      { name: "Nandurbar" },
      { name: "Nashik" },
      { name: "Osmanabad" },
      { name: "Palghar" },
      { name: "Parbhani" },
      { name: "Pune" },
      { name: "Raigad" },
      { name: "Ratnagiri" },
      { name: "Sangli" },
      { name: "Satara" },
      { name: "Sindhudurg" },
      { name: "Solapur" },
      { name: "Thane" },
      { name: "Wardha" },
      { name: "Washim" },
      { name: "Yavatmal" },
    ]
  },
  {
    name: "Manipur",
    nameHi: "मणिपुर",
    nameTe: "మణిపూర్",
    code: "MN",
    districts: [
      { name: "Bishnupur" },
      { name: "Chandel" },
      { name: "Churachandpur" },
      { name: "Imphal East" },
      { name: "Imphal West" },
      { name: "Jiribam" },
      { name: "Kakching" },
      { name: "Kamjong" },
      { name: "Kangpokpi" },
      { name: "Noney" },
      { name: "Pherzawl" },
      { name: "Senapati" },
      { name: "Tamenglong" },
      { name: "Tengnoupal" },
      { name: "Thoubal" },
      { name: "Ukhrul" },
    ]
  },
  {
    name: "Meghalaya",
    nameHi: "मेघालय",
    nameTe: "మేఘాలయ",
    code: "ML",
    districts: [
      { name: "East Garo Hills" },
      { name: "East Jaintia Hills" },
      { name: "East Khasi Hills" },
      { name: "North Garo Hills" },
      { name: "Ri Bhoi" },
      { name: "South Garo Hills" },
      { name: "South West Garo Hills" },
      { name: "South West Khasi Hills" },
      { name: "West Garo Hills" },
      { name: "West Jaintia Hills" },
      { name: "West Khasi Hills" },
    ]
  },
  {
    name: "Mizoram",
    nameHi: "मिज़ोरम",
    nameTe: "మిజోరం",
    code: "MZ",
    districts: [
      { name: "Aizawl" },
      { name: "Champhai" },
      { name: "Hnahthial" },
      { name: "Khawzawl" },
      { name: "Kolasib" },
      { name: "Lawngtlai" },
      { name: "Lunglei" },
      { name: "Mamit" },
      { name: "Saitual" },
      { name: "Serchhip" },
      { name: "Siaha" },
    ]
  },
  {
    name: "Nagaland",
    nameHi: "नागालैंड",
    nameTe: "నాగాలాండ్",
    code: "NL",
    districts: [
      { name: "Dimapur" },
      { name: "Kiphire" },
      { name: "Kohima" },
      { name: "Longleng" },
      { name: "Mokokchung" },
      { name: "Mon" },
      { name: "Peren" },
      { name: "Phek" },
      { name: "Tuensang" },
      { name: "Wokha" },
      { name: "Zunheboto" },
    ]
  },
  {
    name: "Odisha",
    nameHi: "ओडिशा",
    nameTe: "ఒడిశా",
    code: "OD",
    districts: [
      { name: "Angul" },
      { name: "Balangir" },
      { name: "Balasore" },
      { name: "Bargarh" },
      { name: "Bhadrak" },
      { name: "Boudh" },
      { name: "Cuttack" },
      { name: "Deogarh" },
      { name: "Dhenkanal" },
      { name: "Gajapati" },
      { name: "Ganjam" },
      { name: "Jagatsinghpur" },
      { name: "Jajpur" },
      { name: "Jharsuguda" },
      { name: "Kalahandi" },
      { name: "Kandhamal" },
      { name: "Kendrapara" },
      { name: "Kendujhar" },
      { name: "Khordha" },
      { name: "Koraput" },
      { name: "Malkangiri" },
      { name: "Mayurbhanj" },
      { name: "Nabarangpur" },
      { name: "Nayagarh" },
      { name: "Nuapada" },
      { name: "Puri" },
      { name: "Rayagada" },
      { name: "Sambalpur" },
      { name: "Subarnapur" },
      { name: "Sundargarh" },
    ]
  },
  {
    name: "Punjab",
    nameHi: "पंजाब",
    nameTe: "పంజాబ్",
    code: "PB",
    districts: [
      { name: "Amritsar" },
      { name: "Barnala" },
      { name: "Bathinda" },
      { name: "Faridkot" },
      { name: "Fatehgarh Sahib" },
      { name: "Fazilka" },
      { name: "Ferozepur" },
      { name: "Gurdaspur" },
      { name: "Hoshiarpur" },
      { name: "Jalandhar" },
      { name: "Kapurthala" },
      { name: "Ludhiana" },
      { name: "Mansa" },
      { name: "Moga" },
      { name: "Mohali" },
      { name: "Muktsar" },
      { name: "Pathankot" },
      { name: "Patiala" },
      { name: "Rupnagar" },
      { name: "Sangrur" },
      { name: "Shaheed Bhagat Singh Nagar" },
      { name: "Tarn Taran" },
    ]
  },
  {
    name: "Rajasthan",
    nameHi: "राजस्थान",
    nameTe: "రాజస్థాన్",
    code: "RJ",
    districts: [
      { name: "Ajmer" },
      { name: "Alwar" },
      { name: "Banswara" },
      { name: "Baran" },
      { name: "Barmer" },
      { name: "Bharatpur" },
      { name: "Bhilwara" },
      { name: "Bikaner" },
      { name: "Bundi" },
      { name: "Chittorgarh" },
      { name: "Churu" },
      { name: "Dausa" },
      { name: "Dholpur" },
      { name: "Dungarpur" },
      { name: "Hanumangarh" },
      { name: "Jaipur" },
      { name: "Jaisalmer" },
      { name: "Jalore" },
      { name: "Jhalawar" },
      { name: "Jhunjhunu" },
      { name: "Jodhpur" },
      { name: "Karauli" },
      { name: "Kota" },
      { name: "Nagaur" },
      { name: "Pali" },
      { name: "Pratapgarh" },
      { name: "Rajsamand" },
      { name: "Sawai Madhopur" },
      { name: "Sikar" },
      { name: "Sirohi" },
      { name: "Sri Ganganagar" },
      { name: "Tonk" },
      { name: "Udaipur" },
    ]
  },
  {
    name: "Sikkim",
    nameHi: "सिक्किम",
    nameTe: "సిక్కిం",
    code: "SK",
    districts: [
      { name: "East Sikkim" },
      { name: "North Sikkim" },
      { name: "South Sikkim" },
      { name: "West Sikkim" },
    ]
  },
  {
    name: "Tamil Nadu",
    nameHi: "तमिलनाडु",
    nameTe: "తమిళనాడు",
    code: "TN",
    districts: [
      { name: "Ariyalur" },
      { name: "Chengalpattu" },
      { name: "Chennai" },
      { name: "Coimbatore" },
      { name: "Cuddalore" },
      { name: "Dharmapuri" },
      { name: "Dindigul" },
      { name: "Erode" },
      { name: "Kallakurichi" },
      { name: "Kancheepuram" },
      { name: "Karur" },
      { name: "Krishnagiri" },
      { name: "Madurai" },
      { name: "Nagapattinam" },
      { name: "Namakkal" },
      { name: "Nilgiris" },
      { name: "Perambalur" },
      { name: "Pudukkottai" },
      { name: "Ramanathapuram" },
      { name: "Ranipet" },
      { name: "Salem" },
      { name: "Sivaganga" },
      { name: "Tenkasi" },
      { name: "Thanjavur" },
      { name: "Theni" },
      { name: "Thoothukudi" },
      { name: "Tiruchirappalli" },
      { name: "Tirunelveli" },
      { name: "Tirupathur" },
      { name: "Tiruppur" },
      { name: "Tiruvallur" },
      { name: "Tiruvannamalai" },
      { name: "Tiruvarur" },
      { name: "Vellore" },
      { name: "Viluppuram" },
      { name: "Virudhunagar" },
    ]
  },
  {
    name: "Telangana",
    nameHi: "तेलंगाना",
    nameTe: "తెలంగాణ",
    code: "TS",
    districts: [
      { name: "Adilabad" },
      { name: "Bhadradri Kothagudem" },
      { name: "Hyderabad" },
      { name: "Jagtial" },
      { name: "Jangaon" },
      { name: "Jayashankar Bhupalpally" },
      { name: "Jogulamba Gadwal" },
      { name: "Kamareddy" },
      { name: "Karimnagar" },
      { name: "Khammam" },
      { name: "Komaram Bheem Asifabad" },
      { name: "Mahabubabad" },
      { name: "Mahabubnagar" },
      { name: "Mancherial" },
      { name: "Medak" },
      { name: "Medchal-Malkajgiri" },
      { name: "Mulugu" },
      { name: "Nagarkurnool" },
      { name: "Nalgonda" },
      { name: "Narayanpet" },
      { name: "Nirmal" },
      { name: "Nizamabad" },
      { name: "Peddapalli" },
      { name: "Rajanna Sircilla" },
      { name: "Rangareddy" },
      { name: "Sangareddy" },
      { name: "Siddipet" },
      { name: "Suryapet" },
      { name: "Vikarabad" },
      { name: "Wanaparthy" },
      { name: "Warangal Rural" },
      { name: "Warangal Urban" },
      { name: "Yadadri Bhuvanagiri" },
    ]
  },
  {
    name: "Tripura",
    nameHi: "त्रिपुरा",
    nameTe: "త్రిపుర",
    code: "TR",
    districts: [
      { name: "Dhalai" },
      { name: "Gomati" },
      { name: "Khowai" },
      { name: "North Tripura" },
      { name: "Sepahijala" },
      { name: "South Tripura" },
      { name: "Unakoti" },
      { name: "West Tripura" },
    ]
  },
  {
    name: "Uttar Pradesh",
    nameHi: "उत्तर प्रदेश",
    nameTe: "ఉత్తర ప్రదేశ్",
    code: "UP",
    districts: [
      { name: "Agra" },
      { name: "Aligarh" },
      { name: "Ambedkar Nagar" },
      { name: "Amethi" },
      { name: "Amroha" },
      { name: "Auraiya" },
      { name: "Ayodhya" },
      { name: "Azamgarh" },
      { name: "Baghpat" },
      { name: "Bahraich" },
      { name: "Ballia" },
      { name: "Balrampur" },
      { name: "Banda" },
      { name: "Barabanki" },
      { name: "Bareilly" },
      { name: "Basti" },
      { name: "Bhadohi" },
      { name: "Bijnor" },
      { name: "Budaun" },
      { name: "Bulandshahr" },
      { name: "Chandauli" },
      { name: "Chitrakoot" },
      { name: "Deoria" },
      { name: "Etah" },
      { name: "Etawah" },
      { name: "Farrukhabad" },
      { name: "Fatehpur" },
      { name: "Firozabad" },
      { name: "Gautam Buddha Nagar" },
      { name: "Ghaziabad" },
      { name: "Ghazipur" },
      { name: "Gonda" },
      { name: "Gorakhpur" },
      { name: "Hamirpur" },
      { name: "Hapur" },
      { name: "Hardoi" },
      { name: "Hathras" },
      { name: "Jalaun" },
      { name: "Jaunpur" },
      { name: "Jhansi" },
      { name: "Kannauj" },
      { name: "Kanpur Dehat" },
      { name: "Kanpur Nagar" },
      { name: "Kasganj" },
      { name: "Kaushambi" },
      { name: "Kushinagar" },
      { name: "Lakhimpur Kheri" },
      { name: "Lalitpur" },
      { name: "Lucknow" },
      { name: "Maharajganj" },
      { name: "Mahoba" },
      { name: "Mainpuri" },
      { name: "Mathura" },
      { name: "Mau" },
      { name: "Meerut" },
      { name: "Mirzapur" },
      { name: "Moradabad" },
      { name: "Muzaffarnagar" },
      { name: "Pilibhit" },
      { name: "Pratapgarh" },
      { name: "Prayagraj" },
      { name: "Rae Bareli" },
      { name: "Rampur" },
      { name: "Saharanpur" },
      { name: "Sambhal" },
      { name: "Sant Kabir Nagar" },
      { name: "Shahjahanpur" },
      { name: "Shamli" },
      { name: "Shrawasti" },
      { name: "Siddharthnagar" },
      { name: "Sitapur" },
      { name: "Sonbhadra" },
      { name: "Sultanpur" },
      { name: "Unnao" },
      { name: "Varanasi" },
    ]
  },
  {
    name: "Uttarakhand",
    nameHi: "उत्तराखंड",
    nameTe: "ఉత్తరాఖండ్",
    code: "UK",
    districts: [
      { name: "Almora" },
      { name: "Bageshwar" },
      { name: "Chamoli" },
      { name: "Champawat" },
      { name: "Dehradun" },
      { name: "Haridwar" },
      { name: "Nainital" },
      { name: "Pauri Garhwal" },
      { name: "Pithoragarh" },
      { name: "Rudraprayag" },
      { name: "Tehri Garhwal" },
      { name: "Udham Singh Nagar" },
      { name: "Uttarkashi" },
    ]
  },
  {
    name: "West Bengal",
    nameHi: "पश्चिम बंगाल",
    nameTe: "పశ్చిమ బెంగాల్",
    code: "WB",
    districts: [
      { name: "Alipurduar" },
      { name: "Bankura" },
      { name: "Birbhum" },
      { name: "Cooch Behar" },
      { name: "Dakshin Dinajpur" },
      { name: "Darjeeling" },
      { name: "Hooghly" },
      { name: "Howrah" },
      { name: "Jalpaiguri" },
      { name: "Jhargram" },
      { name: "Kalimpong" },
      { name: "Kolkata" },
      { name: "Malda" },
      { name: "Murshidabad" },
      { name: "Nadia" },
      { name: "North 24 Parganas" },
      { name: "Paschim Bardhaman" },
      { name: "Paschim Medinipur" },
      { name: "Purba Bardhaman" },
      { name: "Purba Medinipur" },
      { name: "Purulia" },
      { name: "South 24 Parganas" },
      { name: "Uttar Dinajpur" },
    ]
  },
  // Union Territories
  {
    name: "Andaman and Nicobar Islands",
    nameHi: "अंडमान और निकोबार द्वीप समूह",
    nameTe: "అండమాన్ నికోబార్ దీవులు",
    code: "AN",
    districts: [
      { name: "Nicobar" },
      { name: "North and Middle Andaman" },
      { name: "South Andaman" },
    ]
  },
  {
    name: "Chandigarh",
    nameHi: "चंडीगढ़",
    nameTe: "చండీగఢ్",
    code: "CH",
    districts: [
      { name: "Chandigarh" },
    ]
  },
  {
    name: "Dadra and Nagar Haveli and Daman and Diu",
    nameHi: "दादरा और नगर हवेली और दमन और दीव",
    nameTe: "దాద్రా నగర్ హవేలీ దమన్ డయ్యూ",
    code: "DD",
    districts: [
      { name: "Dadra and Nagar Haveli" },
      { name: "Daman" },
      { name: "Diu" },
    ]
  },
  {
    name: "Jammu and Kashmir",
    nameHi: "जम्मू और कश्मीर",
    nameTe: "జమ్ము కాశ్మీర్",
    code: "JK",
    districts: [
      { name: "Anantnag" },
      { name: "Bandipora" },
      { name: "Baramulla" },
      { name: "Budgam" },
      { name: "Doda" },
      { name: "Ganderbal" },
      { name: "Jammu" },
      { name: "Kathua" },
      { name: "Kishtwar" },
      { name: "Kulgam" },
      { name: "Kupwara" },
      { name: "Poonch" },
      { name: "Pulwama" },
      { name: "Rajouri" },
      { name: "Ramban" },
      { name: "Reasi" },
      { name: "Samba" },
      { name: "Shopian" },
      { name: "Srinagar" },
      { name: "Udhampur" },
    ]
  },
  {
    name: "Ladakh",
    nameHi: "लद्दाख",
    nameTe: "లడఖ్",
    code: "LA",
    districts: [
      { name: "Kargil" },
      { name: "Leh" },
    ]
  },
  {
    name: "Lakshadweep",
    nameHi: "लक्षद्वीप",
    nameTe: "లక్షద్వీప",
    code: "LD",
    districts: [
      { name: "Lakshadweep" },
    ]
  },
  {
    name: "Puducherry",
    nameHi: "पुदुचेरी",
    nameTe: "పుదుచ్చేరి",
    code: "PY",
    districts: [
      { name: "Karaikal" },
      { name: "Mahe" },
      { name: "Puducherry" },
      { name: "Yanam" },
    ]
  },
];

// Helper function to get state by code
export function getStateByCode(code: string): State | undefined {
  return INDIAN_STATES.find(s => s.code === code);
}

// Helper function to get state by name
export function getStateByName(name: string): State | undefined {
  return INDIAN_STATES.find(s => s.name.toLowerCase() === name.toLowerCase());
}

// Helper function to get districts for a state
export function getDistrictsForState(stateCodeOrName: string): District[] {
  const state = getStateByCode(stateCodeOrName) || getStateByName(stateCodeOrName);
  return state?.districts || [];
}
